#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-openwrt-builder
SERVICE_NAME="openwrt-builder"

openwrt_builder_bootstrap

print_info "Type 'openwrt_builder' from a shell prompt to build images to '/data/builds'"

liftoff
