#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

DATA_PATH=${DATA_PATH:-"/data/"}
OPENWRT_BUILD_CACHE=${OPENWRT_BUILD_CACHE:-"FALSE"}
OPENWRT_CHIPSET=${OPENWRT_CHIPSET:-"ipq40xx:generic,mediatek/filogic"}
